Repository BCSDLab/KOIN_OWNER_WEB, pull requests merged in 2024-01, with the labels that each got.

#35 [비밀번호 찾기] 새로운 비밀번호로 변경하기 로직 구현
  src/api/auth/index.ts
  src/page/Auth/FindPassword/CompleteChangePassword/index.tsx
  src/page/Auth/FindPassword/NewPassword/NewPassword.module.scss
  src/page/Auth/FindPassword/NewPassword/index.tsx
  src/page/Auth/FindPassword/SendAuthNumber/index.tsx
  src/page/Auth/FindPassword/hooks/useRouteCheck.ts
  src/query/auth.ts
  src/store/useEmailAuth.ts
Labels: enhancement

#34 [회원가입] 회원가입 페이지 API 연동
  src/api/index.ts
  src/api/register/index.ts
  src/assets/svg/auth/default-file.svg
  src/assets/svg/auth/search-glasses.svg
  src/component/common/CustomModal/CustomModal.module.scss
  src/model/register/index.ts
  src/page/Auth/Signup/SignUp.module.scss
  src/page/Auth/Signup/component/CustomButton/CustomButton.module.scss
  src/page/Auth/Signup/component/CustomButton/index.tsx
  src/page/Auth/Signup/component/ErrorMessage/ErrorMessage.module.scss
  src/page/Auth/Signup/component/UserEmail/UserEmail.module.scss
  src/page/Auth/Signup/component/UserEmail/index.tsx
  src/page/Auth/Signup/component/UserId/UserId.module.scss
  src/page/Auth/Signup/component/UserId/index.tsx
  src/page/Auth/Signup/component/UserPassword/index.tsx
  src/page/Auth/Signup/hooks/useAuthCheck.ts
  src/page/Auth/Signup/hooks/useCheckEmailDuplicate.ts
  src/page/Auth/Signup/hooks/useCheckNext.ts
  src/page/Auth/Signup/hooks/useCheckNextStep.ts
  src/page/Auth/Signup/hooks/useFileController.ts
  src/page/Auth/Signup/hooks/useOwnerData.ts
  src/page/Auth/Signup/hooks/usePasswordConfirm.ts
  src/page/Auth/Signup/hooks/useValidateEmail.ts
  src/page/Auth/Signup/hooks/useVerification.ts
  src/page/Auth/Signup/index.tsx
  src/page/Auth/Signup/types/Owner.ts
  src/page/Auth/Signup/types/Register.ts
  src/page/Auth/Signup/types/RegisterData.ts
  src/page/Auth/Signup/types/User.ts
  src/page/Auth/Signup/utils/parseRegisterData.ts
  src/page/Auth/Signup/view/OwnerDataPage/OwnerData.module.scss
  src/page/Auth/Signup/view/OwnerDataPage/index.tsx
  src/page/Auth/Signup/view/TermsOfServicePage/TermsOfService.module.scss
  src/page/Auth/Signup/view/UserDataPage/UserData.module.scss
  src/page/Auth/Signup/view/UserDataPage/index.tsx
  src/page/ShopRegistration/component/Modal/ConfirmShop/ConfirmShop.module.scss
  src/page/ShopRegistration/component/Modal/ConfirmShop/index.tsx
  src/page/ShopRegistration/component/Modal/SearchShop/SearchShop.module.scss
  src/page/ShopRegistration/component/Modal/SearchShop/index.tsx
  src/page/StoreRegistration/component/Modal/ConfirmStore/index.tsx
  src/page/StoreRegistration/hooks/useSearchStoreName.ts
  src/query/register.ts
  src/store/modalStore.ts
  src/store/registerStore.ts
Labels: enhancement

#37 [가게 등록] 모바일 가게 등록 페이지 로직 및 API 구현
  src/model/shopInfo/ownerShop.ts
  src/page/ShopRegistration/component/InputBox/index.tsx
  src/page/ShopRegistration/component/Modal/Category/index.tsx
  src/page/ShopRegistration/component/Modal/ConfirmShop/index.tsx
  src/page/ShopRegistration/component/Modal/OperateTimeMobile/OperateTimeMobile.module.scss
  src/page/ShopRegistration/component/Modal/OperateTimeMobile/index.tsx
  src/page/ShopRegistration/hooks/useOperateTimeState.ts
  src/page/ShopRegistration/view/Mobile/Main/Main.module.scss
  src/page/ShopRegistration/view/Mobile/Main/index.tsx
  src/page/ShopRegistration/view/Mobile/ShopCategory/index.tsx
  src/page/ShopRegistration/view/Mobile/ShopConfirmation/index.tsx
  src/page/ShopRegistration/view/Mobile/Sub/index.tsx
  src/page/ShopRegistration/view/PC/ShopRegistrationPC.module.scss
  src/page/ShopRegistration/view/PC/index.tsx
  src/store/modalStore.ts
  src/store/shopRegistration.ts
  src/utils/hooks/useImageUpload.ts
Labels: enhancement

#43 [로그인] 회원 정보에 따른 페이지 이동 오류
  src/query/auth.ts
Labels: bug

#55 [가게 등록] 운영시간 휴무일 전체로 선택 시, 시간표에 undefined 나오는 버그 수정
  src/page/ShopRegistration/hooks/CheckSameTime.ts
  src/page/ShopRegistration/view/Mobile/Sub/index.tsx
  src/page/ShopRegistration/view/PC/index.tsx
Labels: bug

#59 [가게 등록] 가게 정보 기입 시 form 양식에 맞지 않는 경우 피드백 생성 추가
  src/page/ShopRegistration/constant/errorMessage.ts
  src/page/ShopRegistration/view/Mobile/Main/Main.module.scss
  src/page/ShopRegistration/view/Mobile/Main/index.tsx
  src/page/ShopRegistration/view/Mobile/ShopCategory/ShopCategory.module.scss
  src/page/ShopRegistration/view/Mobile/ShopCategory/index.tsx
  src/page/ShopRegistration/view/Mobile/Sub/Sub.module.scss
  src/page/ShopRegistration/view/Mobile/Sub/index.tsx
  src/page/ShopRegistration/view/PC/index.tsx
  src/store/shopRegistration.ts
Labels: bug

#61 fix: 메뉴추가후 내상점에 메뉴 업데이트 안되던 부분 수정
  src/assets/svg/addmenu/mobile-single-menu-check-selected.svg
  src/assets/svg/addmenu/mobile-single-menu-check.svg
  src/page/AddMenu/components/AddMenuImgModal/index.tsx
  src/page/AddMenu/components/MenuImage/MenuImage.module.scss
  src/page/AddMenu/components/MenuPrice/MenuPrice.module.scss
  src/page/AddMenu/components/MenuPrice/index.tsx
  src/query/shop.ts
Labels: bug

#63 [메인 페이지] 메인 페이지에 업로드 되지 않는 2개 이미지 변경
  src/page/MyShopPage/components/ShopInfo/ShopInfo.module.scss
  src/page/MyShopPage/components/ShopInfo/index.tsx
Labels: bug

#60 [가게 등록] 가게 정보 기입 완료 후 이미지가 메인 화면에 표시 안됨
  src/page/ShopRegistration/constant/errorMessage.ts
  src/page/ShopRegistration/view/Mobile/Main/index.tsx
  src/page/ShopRegistration/view/PC/index.tsx
  src/utils/hooks/useImageUpload.ts
Labels: bug

#70 [회원가입] 이메일 인증 타이머 추가 및 ErrorMessage 컴포넌트 리팩토링
  package.json
  src/page/Auth/Signup/component/ErrorMessage/index.tsx
  src/page/Auth/Signup/component/UserEmail/index.tsx
  src/page/Auth/Signup/component/UserId/index.tsx
  src/page/Auth/Signup/component/UserPassword/index.tsx
  src/page/Auth/Signup/hooks/useAuthCheck.ts
  src/page/Auth/Signup/hooks/useOwnerData.ts
  src/page/Auth/Signup/hooks/useTimer.ts
  src/page/Auth/Signup/view/OwnerDataPage/index.tsx
  src/page/ShopRegistration/component/Modal/ConfirmShop/index.tsx
  src/query/register.ts
  src/store/shopRegistration.ts
  yarn.lock
Labels: bug, Refactoring

#75 [가게 등록] 모바일 가게 정보 확인 중 결제 옵션 마우스 포인터 삭제
  src/page/ShopRegistration/view/Mobile/ShopConfirmation/ShopConfirmation.module.scss
Labels: bug

#79 가게 등록에서 사진 넣을 때 에러 핸들링
  src/api/uploadFile/Uploadfile.ts
  src/page/ShopRegistration/constant/errorMessage.ts
  src/page/ShopRegistration/view/Mobile/Main/index.tsx
  src/page/ShopRegistration/view/PC/index.tsx
  src/utils/hooks/useImageUpload.ts
Labels: bug

#77 fix: 메뉴 단일 메뉴 선택 로직 추가
  src/page/AddMenu/components/MenuPrice/MenuPrice.module.scss
  src/page/AddMenu/components/MenuPrice/index.tsx
  src/page/AddMenu/index.tsx
  src/query/shop.ts
  src/store/addMenu.ts
Labels: bug

#81 [비밀번호 찾기] 오류시 피드백 추가
  src/assets/svg/error/auth-error.svg
  src/page/Auth/FindPassword/SendAuthNumber/SendAuthNumber.module.scss
  src/page/Auth/FindPassword/SendAuthNumber/index.tsx
  src/query/auth.ts
  src/utils/ts/className.ts
Labels: bug, enhancement

#87 API 엔드포인트 변경에 따른 클라이언트 대응 - 상점의 모든 메뉴 조회
  src/api/shop/index.ts
Labels: enhancement

#85 [내 상점] 가게 정보 중 휴무일 값 누락 수정
  src/page/MyShopPage/components/ShopInfo/index.tsx
Labels: bug

#95 [비밀번호찾기] 인증번호 발송 버튼 위치 수정 및 라벨 수정
  src/page/Auth/FindPassword/SendAuthNumber/index.tsx
Labels: UI

#102 가게명이 길면 글자가 넘치는 버그 수정
  src/page/MyShopPage/components/ShopInfo/ShopInfo.module.scss
  src/page/MyShopPage/components/ShopInfo/index.tsx
Labels: bug

#105 카테고리를 미 선택한 경우에도 메뉴추가 진행이 되던 버그 수정
  src/page/AddMenu/components/MenuCategory/MenuCategory.module.scss
  src/page/AddMenu/components/MenuCategory/index.tsx
  src/page/AddMenu/index.tsx
  src/store/addMenu.ts
Labels: bug, enhancement

#99 미구현 페이지 UI처리
  src/App.tsx
  src/assets/svg/error/page-not-found-error.svg
  src/page/Error/PageNotFound/PageNotFound.module.scss
  src/page/Error/PageNotFound/index.tsx
  src/utils/constant/category.ts
Labels: bug

#108 메뉴추가시 메뉴명을 필수적으로 입력하도록 수정
  src/page/AddMenu/components/MenuCategory/index.tsx
  src/page/AddMenu/components/MenuName/MenuName.module.scss
  src/page/AddMenu/components/MenuName/index.tsx
  src/page/AddMenu/hook/useFormValidation.ts
  src/page/AddMenu/index.tsx
  src/store/addMenu.ts
  src/store/addMenuErrorMessageStore.ts
Labels: bug, Refactoring, QA issue

#110 상점 등록을 하지 않아도 메뉴 추가로직이 실행되는 버그 수정
  src/page/MyShopPage/index.tsx
Labels: QA issue

#113 상점등록을 하지 않아도 가게정보로 이동가능한 버그 수정 리팩토링
  src/App.tsx
  src/page/MyShopPage/index.tsx
  src/query/shop.ts
Labels: Refactoring, QA issue

#111 [내 상점] 가게 정보 수정 모달 추가
  src/api/shop/index.ts
  src/component/common/CustomModal/CustomModal.module.scss
  src/component/common/CustomModal/index.tsx
  src/page/MyShopPage/components/EditShopInfoModal/EditShopInfoModal.module.scss
  src/page/MyShopPage/components/EditShopInfoModal/index.tsx
  src/page/MyShopPage/components/ShopInfo/index.tsx
  src/page/MyShopPage/index.tsx
  src/page/ShopRegistration/component/Modal/OperateTimeMobile/index.tsx
  src/page/ShopRegistration/component/Modal/OperateTimePC/index.tsx
  src/page/ShopRegistration/component/TimePicker/index.tsx
  src/page/ShopRegistration/hooks/useOperateTimeState.ts
  src/query/shop.ts
  src/store/modalStore.ts
Labels: enhancement, QA issue
