Repository BCSDLab/KOIN_OWNER_WEB, pull requests merged in 2024-06, with the labels that each got.

#344 [코인 오너] useStep에서 현재 단계 상태를 추가하여 다음 페이지 로직 통제
  .yarn/cache/fsevents-patch-21ad2b1333-8.zip
  src/page/Auth/hook/useStep.ts
Labels: 🔨 Refactor

#347 [공통] 로그인시 이메일 검증 제거
  .yarn/cache/fsevents-patch-21ad2b1333-8.zip
  .yarnrc.yml
  src/model/auth/index.ts
Labels: ✨ Feature

#353 [DA 구글 태그] 구글 태그 script 추가
  public/index.html
Labels: 🐞 BugFix

#356 [주변 상점] 비밀번호 찾기 진입오류 수정
  src/page/Auth/FindPassword/ChangePassword/index.tsx
  src/page/Auth/FindPassword/Verify/index.tsx
  src/page/Auth/FindPassword/entity.ts
  src/page/Auth/FindPassword/index.tsx
  src/page/Auth/Signup/components/searchShop/index.tsx
  src/page/Auth/Signup/index.tsx
  src/page/Auth/components/Common/index.tsx
Labels: 🐞 BugFix, ❗QA issue

#363 [주변상점] css오류, 로그인페이지 바로가기 오류, 파일삭제 오류 수정
  src/page/Auth/Signup/components/ownerInfoStep/index.tsx
  src/page/Auth/Signup/components/ownerInfoStep/ownerInfoStep.module.scss
  src/page/Auth/Signup/components/phoneStep/index.tsx
  src/page/Auth/Signup/components/phoneStep/phoneStep.module.scss
  src/page/Auth/Signup/components/searchShop/searchShop.module.scss
  src/page/Auth/components/Done/index.module.scss
  src/page/Auth/components/Done/index.tsx
Labels: ❗QA issue
