Repository BCSDLab/KOIN_OWNER_WEB, pull requests merged in 2024-02, with the labels that each got.

#124 fix: "/" 페이지로 이동시 모든 메뉴 데이터 초기화 되도록 수정
  src/page/MyShopPage/index.tsx
Labels: bug

#117 회원가입 에러메세지 관련 오류 수정
  src/page/Auth/Signup/component/CustomButton/CustomButton.module.scss
  src/page/Auth/Signup/component/UserEmail/index.tsx
  src/page/Auth/Signup/component/UserId/index.tsx
  src/page/Auth/Signup/hooks/useAuthCheck.ts
  src/page/Auth/Signup/hooks/useCheckEmailDuplicate.ts
  src/page/Auth/Signup/hooks/useOwnerData.ts
Labels: QA issue

#122 로그인시 상황에 맞는 에러메시지가 표시되도록 수정
  src/model/auth/index.ts
  src/page/AddMenu/components/MenuCategory/index.tsx
  src/page/AddMenu/components/MenuName/index.tsx
  src/page/AddMenu/hook/useFormValidation.ts
  src/page/AddMenu/index.tsx
  src/page/Auth/Login/index.tsx
  src/query/auth.ts
  src/store/errorMessageStore.ts
Labels: QA issue

#120 [가게 등록] 가게 정보 입력 제어 및 저장 실패 시 에러 표현
  src/page/MyShopPage/components/EditShopInfoModal/index.tsx
  src/page/ShopRegistration/component/ConfirmPopup/ConfirmPopup.module.scss
  src/page/ShopRegistration/component/ConfirmPopup/index.tsx
  src/page/ShopRegistration/component/InputBox/InputBox.module.scss
  src/page/ShopRegistration/component/InputBox/index.tsx
  src/page/ShopRegistration/view/Mobile/Sub/index.tsx
  src/page/ShopRegistration/view/PC/ShopRegistrationPC.module.scss
  src/page/ShopRegistration/view/PC/index.tsx
  src/store/shopRegistration.ts
Labels: bug

#126 페이지 라우팅 수정
  src/App.tsx
  src/page/Auth/Login/static/option.ts
  src/utils/constant/category.ts
Labels: QA issue

#130 가게 정보 수정 에러 해결
  package.json
  src/App.tsx
  src/component/common/Toast/index.tsx
  src/page/MyShopPage/components/EditShopInfoModal/EditShopInfoModal.module.scss
  src/page/MyShopPage/components/EditShopInfoModal/index.tsx
  src/page/MyShopPage/components/ShopInfo/ShopInfo.module.scss
  src/page/MyShopPage/components/ShopInfo/index.tsx
  src/page/MyShopPage/index.tsx
  src/page/ShopRegistration/component/Modal/OperateTimePC/index.tsx
  src/page/ShopRegistration/view/Mobile/Main/index.tsx
  src/utils/ts/showToast.ts
  yarn.lock
Labels: bug, QA issue

#129 [회원가입, 가게정보] CSS 이슈 수정
  src/page/Auth/Signup/view/OwnerDataPage/OwnerData.module.scss
  src/page/MyShopPage/components/CatagoryMenuList/CatagoryMenuList.module.scss
Labels: QA issue

#138 [메뉴 삭제] 메뉴삭제 기능 구현
  src/api/shop/index.ts
  src/page/AddMenu/AddMenu.module.scss
  src/page/ModifyMenu/index.tsx
  src/query/menu.ts
Labels: enhancement, QA issue
