Repository BCSDLab/KOIN_OWNER_WEB, pull requests merged in 2024-07, with the labels that each got.

#365 [주변상점]가게검색 뒤로가기 버튼 클릭시 가게 정보 입력으로 가도록 변경
  src/page/Auth/hook/useStep.ts
Labels: ❗QA issue

#370 [비즈니스] 계좌번호 등록 기능 추가
  src/model/shopInfo/myShopInfo.ts
  src/model/shopInfo/ownerShop.ts
  src/page/MyShopPage/components/BankList/index.module.scss
  src/page/MyShopPage/components/BankList/index.tsx
  src/page/MyShopPage/components/EditShopInfoModal/EditShopInfoModal.module.scss
  src/page/MyShopPage/components/EditShopInfoModal/index.tsx
  src/page/MyShopPage/components/ShopInfo/ShopInfo.module.scss
  src/page/MyShopPage/components/ShopInfo/index.tsx
  src/utils/constant/bank.ts
Labels: ✨ Feature

#373 [비즈니스] 회원가입 인증번호 확인 버튼, 토스트 추가
  src/page/Auth/Signup/components/phoneStep/index.tsx
  src/page/Auth/Signup/components/phoneStep/phoneStep.module.scss
Labels: ❗QA issue

#378 [영양사] 영양사 코드 삭제
  src/App.tsx
  src/api/coop/index.ts
  src/api/uploadFile/index.ts
  src/component/common/Header/MobilePanel/index.tsx
  src/component/common/Header/PCPanel/index.tsx
  src/layout/CoopLayout/index.tsx
  src/model/Coop/index.ts
  src/model/auth/index.ts
  src/page/Coop/Coop.module.scss
  src/page/Coop/components/Calendar/Calendar.module.scss
  src/page/Coop/components/Calendar/index.tsx
  src/page/Coop/components/MenuCard/MenuCard.module.scss
  src/page/Coop/components/MenuCard/index.tsx
  src/page/Coop/components/MenuType/MenuType.module.scss
  src/page/Coop/components/MenuType/index.tsx
  src/page/Coop/components/SoldoutModal/SoldoutModal.module.scss
  src/page/Coop/components/SoldoutModal/index.tsx
  src/page/Coop/components/SoldoutToggle/SoldoutToggle.module.scss
  src/page/Coop/components/SoldoutToggle/index.tsx
  src/page/Coop/hook/useGetCurrentMenuType.ts
  src/page/Coop/hook/useGetDayOfWeek.ts
  src/page/Coop/index.tsx
  src/page/CoopPage/index.tsx
  src/page/ManageEvent/AddingEvent/index.tsx
  src/page/ManageEvent/ModifyEvent/index.tsx
  src/query/KeyFactory/coopKeys.ts
  src/query/coop.ts
  src/store/soldoutToggleStore.ts
  src/utils/constant/category.ts
  src/utils/hooks/useSuspenseUser.ts
Labels: 🔨 Refactor
