Repository BCSDLab/KOIN_OWNER_WEB, pull requests merged in 2024-05, with the labels that each got.

#303 [영양사] 주간탭 추가, 품절 모달 수정, 변경된 UI 적용
  .pnp.cjs
  .yarn/cache/dayjs-npm-1.11.10-2b4382efc1-a6b5a3813b.zip
  package.json
  src/api/coop/index.ts
  src/model/Coop/index.ts
  src/page/Coop/components/Calendar/Calendar.module.scss
  src/page/Coop/components/Calendar/index.tsx
  src/page/Coop/components/MenuCard/MenuCard.module.scss
  src/page/Coop/components/MenuCard/index.tsx
  src/page/Coop/components/MenuType/MenuType.module.scss
  src/page/Coop/hook/useGetCurrentMenuType.ts
  src/page/Coop/hook/useGetDayOfWeek.ts
  src/page/Coop/index.tsx
  src/query/coop.ts
  yarn.lock
Labels: ✨ Feature

#306 [공통] 로그인 된 상태에서 새로고침 시 로그인 화면 리다이렉트되는 문제
  src/App.tsx
  src/query/auth.ts
  src/store/useUserTypeStore.ts
Labels: ❗QA issue

#305 [로그인 에러 핸들링] 로그인 에러 시 sendClient 시점 수정
  src/query/auth.ts
Labels: 🐞 BugFix

#309 [공통] 로그아웃 시 세션에 user_type 남아있는 문제
  src/query/auth.ts
Labels: 🐞 BugFix

#311 Feat/#295/event delete alert modal
  src/component/common/Modal/alertModal/alertModal.module.scss
  src/component/common/Modal/alertModal/index.tsx
  src/page/ManageEvent/ModifyEvent/index.tsx
  src/page/MyShopPage/components/EventTable/index.tsx
Labels: ✨ Feature

#316 [영양사] 캠퍼스팀 2차 스프린트 QA 이슈 해결
  src/page/Coop/components/Calendar/Calendar.module.scss
  src/page/Coop/components/MenuCard/MenuCard.module.scss
  src/page/Coop/components/MenuCard/index.tsx
  src/page/Coop/components/SoldoutToggle/SoldoutToggle.module.scss
Labels: 🐞 BugFix, ❗QA issue

#318 [주변상점] 기본 이미지 오류 수정
  .yarn/cache/fsevents-patch-21ad2b1333-8.zip
  src/page/MyShopPage/components/EventTable/EventTable.module.scss
  src/page/MyShopPage/components/EventTable/components/EventCard/EventCard.module.scss
  src/page/MyShopPage/components/EventTable/components/EventCard/index.tsx
  src/page/MyShopPage/components/EventTable/index.tsx
Labels: 🐞 BugFix

#336 [공통] iOS 폰트색상 전역적으로 수정
  src/index.scss
Labels: ❗QA issue
