Repository BCSDLab/KOIN_OWNER_WEB, pull requests merged in 2024-03, with the labels that each got.

#146 메뉴 삭제 버튼 이동, 가게정보 이미지 넘침 현상 수정
  src/page/AddMenu/AddMenu.module.scss
  src/page/AddMenu/components/MenuName/MenuName.module.scss
  src/page/AddMenu/components/MenuName/index.tsx
  src/page/ModifyMenu/index.tsx
  src/page/MyShopPage/components/ShopInfo/ShopInfo.module.scss
Labels: bug, UI

#149 라우팅 url 수정
  src/page/MyShopPage/index.tsx
Labels: bug

#156 카메라 촬영 버튼 동작 안함 수정
  src/page/AddMenu/components/AddMenuImgModal/index.tsx
  src/page/AddMenu/components/MenuImage/index.tsx
Labels: bug

#163 메뉴 가격 추가 버튼 기능 수정
  src/page/AddMenu/components/MenuPrice/index.tsx
Labels: Refactoring

#168 fix: 상점 카테고리 아이디가 사라지는 에러 수정
  src/page/MyShopPage/components/EditShopInfoModal/index.tsx
Labels: bug

#195 단건 파일 업로드에 대해 https:// 삭제
  src/page/AddMenu/hook/useMenuImageUpload.ts
  src/utils/hooks/useImageUpload.ts
Labels: 📬 API

#204 [hotfix] https 삭제
  src/page/Auth/Signup/utils/parseRegisterData.ts
Labels: 🐞 BugFix

#210 [#209] 가격 상태 디폴트값 단일로 변경
  src/store/addMenu.ts
Labels: ✨ Feature

#216 [주변상점] 가격추가 단일로만 가능하도록 변경
  src/page/AddMenu/components/MenuPrice/MenuPrice.module.scss
  src/page/AddMenu/components/MenuPrice/index.tsx
  src/page/ModifyMenu/ModifyMenu.module.scss
Labels: ✨ Feature, 🔨 Refactor
