Repository BCSDLab/KOIN_OWNER_WEB, pull requests merged in 2024-04, with the labels that each got.

#221 [영양사] 영양사 페이지 구현
  src/App.tsx
  src/api/coop/index.ts
  src/assets/svg/coop/photo.svg
  src/component/common/Header/index.tsx
  src/model/Coop/index.ts
  src/page/Coop/Coop.module.scss
  src/page/Coop/components/MenuCard/MenuCard.module.scss
  src/page/Coop/components/MenuCard/index.tsx
  src/page/Coop/components/MenuType/MenuType.module.scss
  src/page/Coop/components/MenuType/index.tsx
  src/page/Coop/components/SoldoutToggle/SoldoutToggle.module.scss
  src/page/Coop/components/SoldoutToggle/index.tsx
  src/page/Coop/index.tsx
  src/query/coop.ts
Labels: ✨ Feature, 🖌 UI

#222 [가게 정보 수정] 가게 정보 수정 모달 카테고리 추가
  src/page/MyShopPage/components/EditShopInfoModal/EditShopInfoModal.module.scss
  src/page/MyShopPage/components/EditShopInfoModal/index.tsx
  src/utils/constant/category.ts
Labels: ✨ Feature

#220 [영양사]사장님, 영양사 url 분기 생성
  src/App.tsx
  src/api/auth/index.ts
  src/api/uploadFile/index.ts
  src/component/common/Header/index.tsx
  src/layout/AuthLayout/index.tsx
  src/layout/CoopLayout/index.tsx
  src/layout/OwnerLayout/index.tsx
  src/model/auth/index.ts
  src/page/AddMenu/index.tsx
  src/page/Auth/Login/index.tsx
  src/page/CoopPage/index.tsx
  src/page/Error/PageNotFound/index.tsx
  src/page/ModifyMenu/index.tsx
  src/page/MyShopPage/components/CatagoryMenuList/index.tsx
  src/page/MyShopPage/index.tsx
  src/query/auth.ts
  src/query/upload.ts
  src/store/errorMessageStore.ts
  src/store/path.ts
  src/store/user.ts
  src/store/userType.ts
  src/utils/constant/category.ts
  src/utils/hooks/useImageUpload.ts
  src/utils/hooks/useImagesUpload.ts
Labels: ✨ Feature

#224 [영양사] 식단 사진 업로드, 품절 기능 구현
  public/index.html
  src/api/uploadFile/index.ts
  src/component/common/CustomModal/CustomModal.module.scss
  src/index.scss
  src/model/Coop/index.ts
  src/page/Coop/Coop.module.scss
  src/page/Coop/components/MenuCard/MenuCard.module.scss
  src/page/Coop/components/MenuCard/index.tsx
  src/page/Coop/components/MenuType/MenuType.module.scss
  src/page/Coop/components/SoldoutToggle/index.tsx
  src/page/Coop/hook/useGetCurrentMenuType.ts
  src/page/Coop/index.tsx
  src/store/soldoutToggleStore.ts
Labels: ✨ Feature, 🖌 UI

#226 [영양사] 식단 이미지 업로드 presigned-url 적용
  src/page/Coop/components/MenuCard/index.tsx
  src/query/KeyFactory/coopKeys.ts
  src/query/coop.ts
Labels: ✨ Feature

#232 [유저 로그인] 로그인 시 에러 메시지 분기별 처리
  src/query/auth.ts
Labels: 🐞 BugFix

#236 [영양사] 이미지 업로드 버그 수정
  src/page/Coop/components/MenuCard/index.tsx
Labels: 🐞 BugFix

#241 [영양사] 품절취소, 품절 레이아웃, 기타 버그 수정
  src/assets/svg/coop/soldout.svg
  src/page/Coop/Coop.module.scss
  src/page/Coop/components/MenuCard/MenuCard.module.scss
  src/page/Coop/components/MenuCard/index.tsx
  src/page/Coop/components/MenuType/MenuType.module.scss
  src/page/Coop/components/SoldoutModal/SoldoutModal.module.scss
  src/page/Coop/components/SoldoutModal/index.tsx
  src/page/Coop/components/SoldoutToggle/index.tsx
Labels: 🐞 BugFix, ✨ Feature, 🖌 UI

#243 [영양사] 반응형으로 다양한 기기 대응
  src/page/Coop/Coop.module.scss
  src/page/Coop/components/MenuCard/MenuCard.module.scss
  src/page/Coop/components/MenuCard/index.tsx
Labels: 🖌 UI

#257 [주변상점] 상점 변경 기능 추가
  src/page/MyShopPage/components/MyShopList/MyShopList.module.scss
  src/page/MyShopPage/components/MyShopList/MyShopList.tsx
  src/page/MyShopPage/index.tsx
  src/query/shop.ts
Labels: 🐞 BugFix, 🔨 Refactor

#264 [영양사] CSS 이슈 수정 및 사파리 이슈 해결
  src/component/common/Header/Header.module.scss
  src/page/Coop/components/MenuCard/MenuCard.module.scss
  src/page/Coop/components/MenuType/MenuType.module.scss
  src/page/Coop/components/SoldoutToggle/SoldoutToggle.module.scss
  src/page/Coop/components/SoldoutToggle/index.tsx
  src/page/Coop/hook/useGetCurrentMenuType.ts
Labels: 🐞 BugFix, 🖌 UI, ❗QA issue

#265 [영양사] 모바일 크롬에서 사진촬영이 불가능한 이슈 수정
  src/page/Coop/components/MenuCard/index.tsx
  src/page/Coop/components/SoldoutToggle/SoldoutToggle.module.scss
Labels: 🐞 BugFix, ❗QA issue

#268 [이벤트 추가] 이벤트 추가 페이지 QA 이슈 해결
  .yarn/cache/fsevents-patch-21ad2b1333-8.zip
  src/page/AddingEvent/AddingEvent.module.scss
  src/page/AddingEvent/index.tsx
  src/page/MyShopPage/index.tsx
Labels: ❗QA issue

#255 [주변상점] 이벤트 추가 시 새로고침
  .yarn/cache/fsevents-patch-21ad2b1333-8.zip
  src/page/MyShopPage/components/EventTable/index.tsx
  src/query/event.ts
Labels: ❗QA issue

#272 [공통] 헤더, 사이드 패널 컴포넌트화
  src/component/common/Header/Header.module.scss
  src/component/common/Header/MobilePanel/MobilePanel.module.scss
  src/component/common/Header/MobilePanel/index.tsx
  src/component/common/Header/PCPanel/PCPanel.module.scss
  src/component/common/Header/PCPanel/index.tsx
  src/component/common/Header/index.tsx
  src/page/MyShopPage/MyShopPage.module.scss
  src/page/MyShopPage/index.tsx
Labels: 🔨 Refactor

#276 [영양사] 품절취소기능 버그 수정
  src/page/Coop/components/MenuCard/index.tsx
  src/page/Coop/components/SoldoutToggle/index.tsx
Labels: 🐞 BugFix

#274 [영양사] 사장님, 영양사 권한에 따른 메뉴 구성 변경
  src/App.tsx
  src/component/common/Header/MobilePanel/MobilePanel.module.scss
  src/component/common/Header/MobilePanel/index.tsx
  src/component/common/Header/PCPanel/index.tsx
  src/component/common/Header/hooks/useMegaMenu.ts
  src/component/common/Header/index.tsx
  src/query/auth.ts
  src/store/useUserTypeStore.ts
  src/utils/constant/category.ts
Labels: ❗QA issue

#270 [주변 상점] 가격 인풋 변경
  src/model/shopInfo/newMenu.ts
  src/page/AddMenu/components/MenuPrice/MenuPrice.module.scss
  src/page/AddMenu/components/MenuPrice/index.tsx
  src/page/AddMenu/index.tsx
  src/page/ModifyMenu/index.tsx
  src/query/menu.ts
Labels: 🐞 BugFix

#290 [영양사] 갤러리에서 사진 선택하도록 수정
  src/page/Coop/components/MenuCard/index.tsx
Labels: ❗QA issue

#286 [주변상점] 이벤트 정보 html 파싱
  .pnp.cjs
  .yarn/cache/dom-serializer-npm-2.0.0-378ebc7200-cd1810544f.zip
  .yarn/cache/domhandler-npm-5.0.3-3ede73dc10-0f58f4a6af.zip
  .yarn/cache/domutils-npm-3.1.0-66c92ef7eb-e5757456dd.zip
  .yarn/cache/entities-npm-4.5.0-7cdb83b832-853f8ebd5b.zip
  .yarn/cache/html-dom-parser-npm-5.0.8-6f09317bfc-f264d58665.zip
  .yarn/cache/html-react-parser-npm-5.1.10-887458c19c-b304921bd0.zip
  .yarn/cache/htmlparser2-npm-9.1.0-5ef8394060-e5f8d51939.zip
  .yarn/cache/inline-style-parser-npm-0.2.3-b8a7023d7a-ed6454de80.zip
  .yarn/cache/react-property-npm-2.0.2-55c6f95f6b-c67fb2590d.zip
  .yarn/cache/style-to-js-npm-1.1.12-55adf1b7c2-8c66706981.zip
  .yarn/cache/style-to-object-npm-1.0.6-b50013e448-5b58295dcc.zip
  package.json
  src/page/MyShopPage/components/EventTable/components/EventCard/components/EventContent/EventContent.module.scss
  src/page/MyShopPage/components/EventTable/components/EventCard/components/EventContent/index.tsx
  src/page/MyShopPage/components/EventTable/components/EventCard/index.tsx
  src/page/MyShopPage/components/EventTable/index.tsx
  yarn.lock
Labels: 🐞 BugFix

#292 [영양사] 품절취소 모달 구현
  src/page/Coop/components/MenuCard/index.tsx
Labels: ✨ Feature, ❗QA issue

#273 [유저 정보] 유저 정보를 직접 받아오는 훅 추가
  src/api/auth/index.ts
  src/api/coop/index.ts
  src/component/common/Header/MobilePanel/index.tsx
  src/component/common/Header/index.tsx
  src/model/Coop/index.ts
  src/model/auth/index.ts
  src/query/KeyFactory/coopKeys.ts
  src/query/KeyFactory/ownerKeys.ts
  src/query/KeyFactory/userKeys.ts
  src/query/coop.ts
  src/query/owner.ts
  src/query/shop.ts
  src/utils/hooks/useSuspenseUser.ts
Labels: 🔨 Refactor
